(() => {
  const language = localStorage.getItem('floresUniverseLanguage') || 'es';
  const codeMap = { es:'ES', en:'EN', pt:'PT', fr:'FR', it:'IT' };
  const common = {
    es:{brand_tag:'Libros que conservan nuestras raíces',nav_inicio:'Inicio',nav_libro:'El libro',nav_recetas:'Recetas',nav_preguntas:'Preguntas',header_cta:'Comprar por {price}',eyebrow:'TRADICIÓN · CULTURA · FAMILIA',hero_buy:'🛒 Comprar ahora — {price}.00',hero_secondary:'Conocer el contenido ↓',trust_digital:'✓ Acceso digital',trust_secure:'✓ Pago seguro con Payhip',trust_delivery:'✓ Entrega digital',story_kicker:'MÁS QUE UN LIBRO',feature1_title:'Tradición',feature1_text:'Recetas y sabores inspirados en nuestra cultura gastronómica.',feature2_title:'Contenido organizado',feature2_text:'Información presentada de forma práctica para consultar desde tus dispositivos.',feature3_title:'Para compartir',feature3_text:'Ideal para disfrutar en familia y conservar nuestras raíces.',recipe_kicker:'¿QUÉ ENCONTRARÁS?',bonus_kicker:'BONO ESPECIAL',bonus_title:'Bono especial por tu compra',bonus_cta:'🎁 Comprar y recibir mi bono — {price}.00',preview_kicker:'HECHO PARA DISFRUTAR',preview_title:'Tu colección digital de sabores nicas',preview_text:'Consulta tu libro desde computadora, tablet o teléfono y vuelve a tus recetas cuando quieras.',preview_feature1:'📱 Digital',preview_feature2:'🇳🇮 Tradición nicaragüense',preview_feature3:'❤️ Para compartir',offer_kicker:'OFERTA ACTUAL',offer_text:'Recibe el libro digital y comienza a disfrutar nuestros sabores tradicionales.',offer_note:'Pago procesado por Payhip · Opciones disponibles según tu región.',price_label:'Precio',offer_cta:'Comprar el libro',faq_kicker:'PREGUNTAS FRECUENTES',faq_title:'Antes de comprar',final_title:'Un pedacito de Nicaragua en cada página 🇳🇮',final_text:'Conservemos nuestras raíces a través de los sabores que compartimos.',footer_tag:'Flores Universo · Libros que conservan nuestras raíces.',footer_home:'← Volver a Flores Universo',book_badge:'SABORES<br>DE NICARAGUA'},
    en:{brand_tag:'Books that preserve our roots',nav_inicio:'Home',nav_libro:'The book',nav_recetas:'Recipes',nav_preguntas:'Questions',header_cta:'Buy for {price}',eyebrow:'TRADITION · CULTURE · FAMILY',hero_buy:'🛒 Buy now — {price}.00',hero_secondary:'Explore the content ↓',trust_digital:'✓ Digital access',trust_secure:'✓ Secure payment with Payhip',trust_delivery:'✓ Digital delivery',story_kicker:'MORE THAN A BOOK',feature1_title:'Tradition',feature1_text:'Recipes and flavors inspired by our culinary culture.',feature2_title:'Organized content',feature2_text:'Information presented in a practical format for your devices.',feature3_title:'Made to share',feature3_text:'Ideal for enjoying with family and preserving our roots.',recipe_kicker:'WHAT WILL YOU FIND?',bonus_kicker:'SPECIAL BONUS',bonus_title:'Special bonus with your purchase',bonus_cta:'🎁 Buy and receive my bonus — {price}.00',preview_kicker:'MADE TO ENJOY',preview_title:'Your digital collection of Nicaraguan flavors',preview_text:'Read your book on a computer, tablet, or phone and return to your recipes anytime.',preview_feature1:'📱 Digital',preview_feature2:'🇳🇮 Nicaraguan tradition',preview_feature3:'❤️ Made to share',offer_kicker:'CURRENT OFFER',offer_text:'Receive the digital book and start enjoying our traditional flavors.',offer_note:'Payment processed by Payhip · Options available according to your region.',price_label:'Price',offer_cta:'Buy the book',faq_kicker:'FREQUENTLY ASKED QUESTIONS',faq_title:'Before you buy',final_title:'A little piece of Nicaragua on every page 🇳🇮',final_text:'Let us preserve our roots through the flavors we share.',footer_tag:'Flores Universo · Books that preserve our roots.',footer_home:'← Back to Flores Universo',book_badge:'FLAVORS<br>OF NICARAGUA'},
    pt:{brand_tag:'Livros que preservam nossas raízes',nav_inicio:'Início',nav_libro:'O livro',nav_recetas:'Receitas',nav_preguntas:'Perguntas',header_cta:'Comprar por {price}',eyebrow:'TRADIÇÃO · CULTURA · FAMÍLIA',hero_buy:'🛒 Comprar agora — {price}.00',hero_secondary:'Conheça o conteúdo ↓',trust_digital:'✓ Acesso digital',trust_secure:'✓ Pagamento seguro com Payhip',trust_delivery:'✓ Entrega digital',story_kicker:'MAIS QUE UM LIVRO',feature1_title:'Tradição',feature1_text:'Receitas e sabores inspirados em nossa cultura gastronômica.',feature2_title:'Conteúdo organizado',feature2_text:'Informações apresentadas de forma prática para consultar em seus dispositivos.',feature3_title:'Para compartilhar',feature3_text:'Ideal para aproveitar em família e preservar nossas raízes.',recipe_kicker:'O QUE VOCÊ ENCONTRARÁ?',bonus_kicker:'BÔNUS ESPECIAL',bonus_title:'Bônus especial pela sua compra',bonus_cta:'🎁 Comprar e receber meu bônus — {price}.00',preview_kicker:'FEITO PARA DESFRUTAR',preview_title:'Sua coleção digital de sabores nicaraguenses',preview_text:'Consulte seu livro no computador, tablet ou telefone e volte às suas receitas quando quiser.',preview_feature1:'📱 Digital',preview_feature2:'🇳🇮 Tradição nicaraguense',preview_feature3:'❤️ Para compartilhar',offer_kicker:'OFERTA ATUAL',offer_text:'Receba o livro digital e comece a aproveitar nossos sabores tradicionais.',offer_note:'Pagamento processado pelo Payhip · Opções disponíveis de acordo com sua região.',price_label:'Preço',offer_cta:'Comprar o livro',faq_kicker:'PERGUNTAS FREQUENTES',faq_title:'Antes de comprar',final_title:'Um pedacinho da Nicarágua em cada página 🇳🇮',final_text:'Preservemos nossas raízes através dos sabores que compartilhamos.',footer_tag:'Flores Universo · Livros que preservam nossas raízes.',footer_home:'← Voltar para Flores Universo',book_badge:'SABORES<br>DA NICARÁGUA'},
    fr:{brand_tag:'Des livres qui préservent nos racines',nav_inicio:'Accueil',nav_libro:'Le livre',nav_recetas:'Recettes',nav_preguntas:'Questions',header_cta:'Acheter pour {price}',eyebrow:'TRADITION · CULTURE · FAMILLE',hero_buy:'🛒 Acheter maintenant — {price}.00',hero_secondary:'Découvrir le contenu ↓',trust_digital:'✓ Accès numérique',trust_secure:'✓ Paiement sécurisé avec Payhip',trust_delivery:'✓ Livraison numérique',story_kicker:'PLUS QU’UN LIVRE',feature1_title:'Tradition',feature1_text:'Recettes et saveurs inspirées de notre culture gastronomique.',feature2_title:'Contenu organisé',feature2_text:'Des informations présentées de manière pratique sur vos appareils.',feature3_title:'À partager',feature3_text:'Idéal pour profiter en famille et préserver nos racines.',recipe_kicker:'QUE TROUVEREZ-VOUS ?',bonus_kicker:'BONUS SPÉCIAL',bonus_title:'Bonus spécial pour votre achat',bonus_cta:'🎁 Acheter et recevoir mon bonus — {price}.00',preview_kicker:'FAIT POUR ÊTRE DÉGUSTÉ',preview_title:'Votre collection numérique des saveurs du Nicaragua',preview_text:'Consultez votre livre sur ordinateur, tablette ou téléphone et retrouvez vos recettes quand vous le souhaitez.',preview_feature1:'📱 Numérique',preview_feature2:'🇳🇮 Tradition nicaraguayenne',preview_feature3:'❤️ À partager',offer_kicker:'OFFRE ACTUELLE',offer_text:'Recevez le livre numérique et commencez à découvrir nos saveurs traditionnelles.',offer_note:'Paiement traité par Payhip · Options disponibles selon votre région.',price_label:'Prix',offer_cta:'Acheter le livre',faq_kicker:'QUESTIONS FRÉQUENTES',faq_title:'Avant d’acheter',final_title:'Un petit morceau du Nicaragua à chaque page 🇳🇮',final_text:'Préservons nos racines à travers les saveurs que nous partageons.',footer_tag:'Flores Universo · Des livres qui préservent nos racines.',footer_home:'← Retour à Flores Universo',book_badge:'SAVEURS<br>DU NICARAGUA'},
    it:{brand_tag:'Libri che conservano le nostre radici',nav_inicio:'Home',nav_libro:'Il libro',nav_recetas:'Ricette',nav_preguntas:'Domande',header_cta:'Acquista per {price}',eyebrow:'TRADIZIONE · CULTURA · FAMIGLIA',hero_buy:'🛒 Acquista ora — {price}.00',hero_secondary:'Scopri il contenuto ↓',trust_digital:'✓ Accesso digitale',trust_secure:'✓ Pagamento sicuro con Payhip',trust_delivery:'✓ Consegna digitale',story_kicker:'PIÙ DI UN LIBRO',feature1_title:'Tradizione',feature1_text:'Ricette e sapori ispirati alla nostra cultura gastronomica.',feature2_title:'Contenuto organizzato',feature2_text:'Informazioni presentate in modo pratico per i tuoi dispositivi.',feature3_title:'Da condividere',feature3_text:'Ideale da gustare in famiglia e per conservare le nostre radici.',recipe_kicker:'COSA TROVERAI?',bonus_kicker:'BONUS SPECIALE',bonus_title:'Bonus speciale con il tuo acquisto',bonus_cta:'🎁 Acquista e ricevi il mio bonus — {price}.00',preview_kicker:'PENSATO PER ESSERE GUSTATO',preview_title:'La tua collezione digitale dei sapori nicaraguensi',preview_text:'Consulta il libro da computer, tablet o telefono e torna alle tue ricette quando vuoi.',preview_feature1:'📱 Digitale',preview_feature2:'🇳🇮 Tradizione nicaraguense',preview_feature3:'❤️ Da condividere',offer_kicker:'OFFERTA ATTUALE',offer_text:'Ricevi il libro digitale e inizia a gustare i nostri sapori tradizionali.',offer_note:'Pagamento elaborato da Payhip · Opzioni disponibili in base alla tua regione.',price_label:'Prezzo',offer_cta:'Acquista il libro',faq_kicker:'DOMANDE FREQUENTI',faq_title:'Prima di acquistare',final_title:'Un piccolo pezzo di Nicaragua in ogni pagina 🇳🇮',final_text:'Conserviamo le nostre radici attraverso i sapori che condividiamo.',footer_tag:'Flores Universo · Libri che conservano le nostre radici.',footer_home:'← Torna a Flores Universo',book_badge:'SAPORI<br>DEL NICARAGUA'}
  };

  const pages = {
    cocina:{
      price:'US$ 12', title:{es:'Cocina Nicaragüense 2.0',en:'Nicaraguan Cuisine 2.0',pt:'Culinária Nicaraguense 2.0',fr:'Cuisine nicaraguayenne 2.0',it:'Cucina Nicaraguense 2.0'}, lead:{es:'Lleva a tu cocina los sabores que nos conectan con Nicaragua.',en:'Bring to your kitchen the flavors that connect us to Nicaragua.',pt:'Leve para sua cozinha os sabores que nos conectam à Nicarágua.',fr:'Apportez à votre cuisine les saveurs qui nous relient au Nicaragua.',it:'Porta nella tua cucina i sapori che ci uniscono al Nicaragua.'}, hero_text:{es:'Un recetario digital creado para disfrutar platos tradicionales nicaragüenses con explicaciones claras y prácticas, desde casa.',en:'A digital cookbook created to enjoy traditional Nicaraguan dishes with clear, practical instructions from home.',pt:'Um livro digital criado para aproveitar pratos tradicionais nicaraguenses com explicações claras e práticas em casa.',fr:'Un livre de recettes numérique pour savourer les plats traditionnels nicaraguayens avec des explications claires et pratiques chez vous.',it:'Un ricettario digitale creato per gustare piatti tradizionali nicaraguensi con spiegazioni chiare e pratiche, da casa.'}, story_title:{es:'Una forma de llevar Nicaragua a tu mesa',en:'A way to bring Nicaragua to your table',pt:'Uma forma de levar a Nicarágua à sua mesa',fr:'Une façon d’apporter le Nicaragua à votre table',it:'Un modo per portare il Nicaragua sulla tua tavola'}, story_text:{es:'La cocina nicaragüense guarda recuerdos, celebraciones y costumbres que pasan de generación en generación. Este libro reúne parte de esa riqueza en un formato digital pensado para consultar, cocinar y compartir.',en:'Nicaraguan cuisine holds memories, celebrations, and traditions passed from generation to generation. This book brings together part of that richness in a digital format made to read, cook, and share.',pt:'A culinária nicaraguense guarda memórias, celebrações e costumes passados de geração em geração. Este livro reúne parte dessa riqueza em um formato digital feito para consultar, cozinhar e compartilhar.',fr:'La cuisine nicaraguayenne conserve des souvenirs, des célébrations et des traditions transmises de génération en génération. Ce livre en rassemble une partie dans un format numérique pensé pour consulter, cuisiner et partager.',it:'La cucina nicaraguense custodisce ricordi, celebrazioni e tradizioni tramandate di generazione in generazione. Questo libro ne raccoglie una parte in un formato digitale pensato per consultare, cucinare e condividere.'},
      features:{es:[['Sabores de siempre','Recetas inspiradas en preparaciones tradicionales de nuestra tierra.'],['Explicado paso a paso','Contenido organizado para que puedas seguir cada preparación con mayor facilidad.'],['Para compartir','Ideal para cocinar en familia y conservar nuestras tradiciones.']]}
    },
    bebidas:{price:'US$ 15', title:{es:'Bebidas Nica',en:'Bebidas Nica',pt:'Bebidas Nica',fr:'Bebidas Nica',it:'Bebidas Nica'}, lead:{es:'Descubre bebidas tradicionales de Nicaragua y lleva a tu mesa sabores refrescantes, caseros y llenos de identidad.',en:'Discover traditional Nicaraguan drinks and bring refreshing, homemade flavors full of identity to your table.',pt:'Descubra bebidas tradicionais da Nicarágua e leve à sua mesa sabores refrescantes, caseiros e cheios de identidade.',fr:'Découvrez les boissons traditionnelles du Nicaragua et apportez à votre table des saveurs rafraîchissantes, maison et pleines d’identité.',it:'Scopri le bevande tradizionali del Nicaragua e porta sulla tua tavola sapori freschi, genuini e ricchi di identità.'}, hero_text:{es:'Una colección digital para conocer y preparar bebidas que forman parte de la tradición nicaragüense. Un formato digital pensado para consultar, disfrutar y compartir.',en:'A digital collection to discover and prepare drinks that are part of Nicaraguan tradition. A format made to read, enjoy, and share.',pt:'Uma coleção digital para conhecer e preparar bebidas que fazem parte da tradição nicaraguense. Um formato feito para consultar, desfrutar e compartilhar.',fr:'Une collection numérique pour découvrir et préparer les boissons qui font partie de la tradition nicaraguayenne. Un format pensé pour consulter, savourer et partager.',it:'Una raccolta digitale per conoscere e preparare bevande che fanno parte della tradizione nicaraguense. Un formato pensato per consultare, gustare e condividere.'}, story_title:{es:'Una forma de llevar Nicaragua a tu hogar',en:'A way to bring Nicaragua into your home',pt:'Uma forma de levar a Nicarágua para sua casa',fr:'Une façon d’apporter le Nicaragua chez vous',it:'Un modo per portare il Nicaragua a casa tua'}, story_text:{es:'Una colección digital para conocer y preparar bebidas que forman parte de la tradición nicaragüense. Cada preparación conecta ingredientes, costumbres y recuerdos de nuestra tierra.',en:'A digital collection to discover and prepare drinks that are part of Nicaraguan tradition. Each preparation connects ingredients, customs, and memories of our homeland.',pt:'Uma coleção digital para conhecer e preparar bebidas da tradição nicaraguense. Cada preparação conecta ingredientes, costumes e memórias de nossa terra.',fr:'Une collection numérique pour découvrir et préparer les boissons de la tradition nicaraguayenne. Chaque préparation relie ingrédients, coutumes et souvenirs de notre terre.',it:'Una raccolta digitale per conoscere e preparare bevande della tradizione nicaraguense. Ogni preparazione unisce ingredienti, usanze e ricordi della nostra terra.'},
      features:{es:[['Tradición','Recetas y sabores inspirados en nuestra cultura gastronómica.'],['Contenido organizado','Información presentada de forma práctica para consultar desde tus dispositivos.'],['Para compartir','Ideal para disfrutar en familia y conservar nuestras raíces.']]}
    },
    postres:{price:'US$ 35', title:{es:'Postres y dulces con sabor a Nicaragua',en:'Desserts and sweets with the flavor of Nicaragua',pt:'Doces e sobremesas com sabor da Nicarágua',fr:'Desserts et douceurs aux saveurs du Nicaragua',it:'Dolci e dessert al sapore del Nicaragua'}, lead:{es:'40 recetas de postres y dulces tradicionales para disfrutar la parte más dulce de la gastronomía nicaragüense.',en:'40 traditional dessert and sweet recipes to enjoy the sweetest side of Nicaraguan cuisine.',pt:'40 receitas de doces e sobremesas tradicionais para aproveitar o lado mais doce da culinária nicaraguense.',fr:'40 recettes de desserts et douceurs traditionnels pour découvrir le côté le plus sucré de la gastronomie nicaraguayenne.',it:'40 ricette di dolci e dessert tradizionali per gustare il lato più dolce della gastronomia nicaraguense.'}, hero_text:{es:'Un recorrido por recetas dulces, tradiciones y sabores que forman parte de nuestras celebraciones y recuerdos. Un formato digital pensado para consultar, disfrutar y compartir.',en:'A journey through sweet recipes, traditions, and flavors that are part of our celebrations and memories. A digital format made to read, enjoy, and share.',pt:'Uma viagem por receitas doces, tradições e sabores que fazem parte de nossas celebrações e lembranças. Um formato digital feito para consultar, desfrutar e compartilhar.',fr:'Un voyage à travers des recettes sucrées, des traditions et des saveurs qui font partie de nos célébrations et souvenirs. Un format numérique pensé pour consulter, savourer et partager.',it:'Un viaggio tra ricette dolci, tradizioni e sapori che fanno parte delle nostre celebrazioni e dei nostri ricordi. Un formato digitale pensato per consultare, gustare e condividere.'}, story_title:{es:'Una forma de llevar Nicaragua a tu hogar',en:'A way to bring Nicaragua into your home',pt:'Uma forma de levar a Nicarágua para sua casa',fr:'Une façon d’apporter le Nicaragua chez vous',it:'Un modo per portare il Nicaragua a casa tua'}, story_text:{es:'Un recorrido por recetas dulces, tradiciones y sabores que forman parte de nuestras celebraciones y recuerdos. Cada preparación conecta ingredientes, costumbres y recuerdos de nuestra tierra.',en:'A journey through sweet recipes, traditions, and flavors that are part of our celebrations and memories. Each preparation connects ingredients, customs, and memories of our homeland.',pt:'Uma viagem por receitas doces, tradições e sabores que fazem parte de nossas celebrações e lembranças. Cada preparação conecta ingredientes, costumes e memórias de nossa terra.',fr:'Un voyage à travers des recettes sucrées, des traditions et des saveurs qui font partie de nos célébrations et souvenirs. Chaque préparation relie ingrédients, coutumes et souvenirs de notre terre.',it:'Un viaggio tra ricette dolci, tradizioni e sapori che fanno parte delle nostre celebrazioni e dei nostri ricordi. Ogni preparazione unisce ingredienti, usanze e ricordi della nostra terra.'},
      features:{es:[['Tradición','Recetas y sabores inspirados en nuestra cultura gastronómica.'],['Contenido organizado','Información presentada de forma práctica para consultar desde tus dispositivos.'],['Para compartir','Ideal para disfrutar en familia y conservar nuestras raíces.']]}
    }
  };

  const translations = common[language] || common.es;
  const page = pages[document.body.dataset.landing] || pages.cocina;
  const L = (obj) => obj?.[language] ?? obj?.es ?? '';
  const set = (selector,keyName) => { const el=document.querySelector(selector); if(el && translations[keyName]!==undefined) el.innerHTML=String(translations[keyName]).replace('{price}',page.price); };
  document.documentElement.lang=language;
  document.querySelector('.landing-language')?.replaceChildren(document.createTextNode(codeMap[language]||'ES'));
  set('[data-i18n="brand_tag"]','brand_tag');
  ['nav_inicio','nav_libro','nav_recetas','nav_preguntas','header_cta','eyebrow','hero_buy','hero_secondary','trust_digital','trust_secure','trust_delivery','book_badge','story_kicker','story_title','story_text','recipe_kicker','bonus_kicker','bonus_title','bonus_cta','preview_kicker','preview_title','preview_text','preview_feature1','preview_feature2','preview_feature3','offer_kicker','offer_text','offer_note','price_label','offer_cta','faq_kicker','faq_title','final_title','final_text','footer_tag','footer_home'].forEach(k=>set(`[data-i18n="${k}"]`,k));
  const hero= document.querySelector('[data-i18n="hero_lead"]'); if(hero) hero.innerHTML=L(page.lead);
  const heroText= document.querySelector('[data-i18n="hero_text"]'); if(heroText) heroText.innerHTML=L(page.hero_text);
  const storyTitle=document.querySelector('[data-i18n="story_title"]'); if(storyTitle) storyTitle.innerHTML=L(page.story_title);
  const storyText=document.querySelector('[data-i18n="story_text"]'); if(storyText) storyText.innerHTML=L(page.story_text);
  const titleEl=document.querySelector('title'); if(titleEl) titleEl.textContent=L(page.title)+' | Flores Universo';
  const meta=document.querySelector('meta[name="description"]'); if(meta) meta.setAttribute('content',L(page.lead));
  const img=document.querySelector('[data-i18n-alt="hero_book_alt"]'); if(img){img.alt=L({es:document.body.dataset.landing==='cocina'?'Portada de Cocina Nicaragüense 2.0':document.body.dataset.landing==='bebidas'?'Portada de Bebidas Nica':'Portada de Postres y dulces con sabor a Nicaragua',en:document.body.dataset.landing==='cocina'?'Cocina Nicaragüense 2.0 cover':document.body.dataset.landing==='bebidas'?'Bebidas Nica cover':'Desserts and sweets with Nicaraguan flavor',pt:document.body.dataset.landing==='cocina'?'Capa de Culinária Nicaraguense 2.0':document.body.dataset.landing==='bebidas'?'Capa de Bebidas Nica':'Capa de Doces e sobremesas da Nicarágua',fr:document.body.dataset.landing==='cocina'?'Couverture de Cuisine nicaraguayenne 2.0':document.body.dataset.landing==='bebidas'?'Couverture de Bebidas Nica':'Couverture de desserts du Nicaragua',it:document.body.dataset.landing==='cocina'?'Copertina di Cucina Nicaraguense 2.0':document.body.dataset.landing==='bebidas'?'Copertina di Bebidas Nica':'Copertina di dolci e dessert del Nicaragua'});}
  const titleNode=document.querySelector('[data-i18n="hero_title"]'); if(titleNode) titleNode.innerHTML=L(page.title);
  const featureCards=document.querySelectorAll('.dish-grid > div'); const f=page.features[language]||page.features.es; featureCards.forEach((c,i)=>{ if(f[i]){c.querySelector('h3').textContent=f[i][0]; c.querySelector('p').textContent=f[i][1];}});
  const recCards=document.querySelectorAll('.recipe-card');
  const recipeMap={
    cocina:{es:[['Gallo Pinto','El plato más icónico de Nicaragua.'],['Indio Viejo','Una preparación tradicional con historia y sabor.'],['Baho','Un sabor único de nuestra tierra.'],['Vigorón','La combinación de yuca, chicharrón y ensalada de repollo.'],['Sopa de Queso','Cremosa, reconfortante y deliciosa.'],['Nacatamal','Tradición en cada bocado.'],['Sopa de Marisco','El sabor del mar en nuestra mesa.'],['Arroz Aguado','Un plato tradicional para toda ocasión.']]},
    bebidas:{es:[['Pinolillo','Una bebida emblemática que nos identifica.'],['Tiste','Refrescante, nutritivo y con historia.'],['Pozol','Una bebida ancestral de gran tradición.'],['Chicha de Maíz','Un clásico que nunca falta.'],['Fresco de Cacao','El sabor único del cacao nicaragüense.'],['Horchata Nicaragüense','Aromática y deliciosa.']]},
    postres:{es:[['Quesillo','El postre más popular de Nicaragua.'],['Tres Leches Nica','Suave, cremoso e irresistible.'],['Arroz con Leche','Tradición y sabor en cada cucharada.'],['Hojaldras','Crujientes y perfectas para toda ocasión.'],['Sopa Borracha','Un postre único de nuestra cultura.'],['Dulce de Cacao','Un sabor tradicional con raíces nicaragüenses.']]}
  };
  const recipeTranslations={
    en:{cocina:[['Gallo Pinto','Nicaragua’s most iconic dish.'],['Indio Viejo','A traditional preparation with history and flavor.'],['Baho','A unique taste of our homeland.'],['Vigorón','Yuca, pork crackling, and cabbage salad together.'],['Cheese Soup','Creamy, comforting, and delicious.'],['Nacatamal','Tradition in every bite.'],['Seafood Soup','The flavor of the sea at our table.'],['Arroz Aguado','A traditional dish for any occasion.']],bebidas:[['Pinolillo','An emblematic drink that represents us.'],['Tiste','Refreshing, nutritious, and full of history.'],['Pozol','An ancestral drink with deep tradition.'],['Corn Chicha','A classic that is always present.'],['Cacao Drink','The unique flavor of Nicaraguan cacao.'],['Nicaraguan Horchata','Aromatic and delicious.']],postres:[['Quesillo','A beloved Nicaraguan sweet.'],['Nicaraguan Tres Leches','Soft, creamy, and irresistible.'],['Rice Pudding','Tradition and flavor in every spoonful.'],['Hojaldras','Crispy and perfect for any occasion.'],['Sopa Borracha','A unique sweet from our culture.'],['Cacao Sweet','A traditional flavor rooted in Nicaragua.']]},
    pt:{cocina:[['Gallo Pinto','O prato mais emblemático da Nicarágua.'],['Indio Viejo','Uma preparação tradicional com história e sabor.'],['Baho','Um sabor único de nossa terra.'],['Vigorón','A combinação de mandioca, torresmo e salada de repolho.'],['Sopa de Queijo','Cremosa, reconfortante e deliciosa.'],['Nacatamal','Tradição em cada mordida.'],['Sopa de Frutos do Mar','O sabor do mar à nossa mesa.'],['Arroz Aguado','Um prato tradicional para qualquer ocasião.']],bebidas:[['Pinolillo','Uma bebida emblemática que nos representa.'],['Tiste','Refrescante, nutritivo e cheio de história.'],['Pozol','Uma bebida ancestral de grande tradição.'],['Chicha de Milho','Um clássico que nunca falta.'],['Bebida de Cacau','O sabor único do cacau nicaraguense.'],['Horchata Nicaraguense','Aromática e deliciosa.']],postres:[['Quesillo','Um doce muito querido na Nicarágua.'],['Tres Leches Nica','Macio, cremoso e irresistível.'],['Arroz com Leite','Tradição e sabor em cada colherada.'],['Hojaldras','Crocantes e perfeitas para qualquer ocasião.'],['Sopa Borracha','Um doce único de nossa cultura.'],['Doce de Cacau','Um sabor tradicional com raízes nicaraguenses.']]},
    fr:{cocina:[['Gallo Pinto','Le plat le plus emblématique du Nicaragua.'],['Indio Viejo','Une préparation traditionnelle pleine d’histoire et de saveur.'],['Baho','Une saveur unique de notre terre.'],['Vigorón','Yuca, couenne de porc et salade de chou.'],['Soupe au fromage','Crémeuse, réconfortante et délicieuse.'],['Nacatamal','La tradition à chaque bouchée.'],['Soupe de fruits de mer','La saveur de la mer à notre table.'],['Arroz Aguado','Un plat traditionnel pour toutes les occasions.']],bebidas:[['Pinolillo','Une boisson emblématique qui nous représente.'],['Tiste','Rafraîchissante, nutritive et chargée d’histoire.'],['Pozol','Une boisson ancestrale de grande tradition.'],['Chicha de maïs','Un classique qui ne manque jamais.'],['Boisson au cacao','La saveur unique du cacao nicaraguayen.'],['Horchata nicaraguayenne','Aromatique et délicieuse.']],postres:[['Quesillo','Une douceur très appréciée au Nicaragua.'],['Tres Leches nica','Doux, crémeux et irrésistible.'],['Riz au lait','Tradition et saveur à chaque cuillerée.'],['Hojaldras','Croustillantes et parfaites en toute occasion.'],['Sopa Borracha','Une douceur unique de notre culture.'],['Douceur au cacao','Une saveur traditionnelle aux racines nicaraguayennes.']]},
    it:{cocina:[['Gallo Pinto','Il piatto più iconico del Nicaragua.'],['Indio Viejo','Una preparazione tradizionale ricca di storia e sapore.'],['Baho','Un gusto unico della nostra terra.'],['Vigorón','Yuca, ciccioli e insalata di cavolo.'],['Zuppa di formaggio','Cremosa, confortante e deliziosa.'],['Nacatamal','Tradizione in ogni boccone.'],['Zuppa di frutti di mare','Il sapore del mare sulla nostra tavola.'],['Arroz Aguado','Un piatto tradizionale per ogni occasione.']],bebidas:[['Pinolillo','Una bevanda emblematica che ci rappresenta.'],['Tiste','Rinfrescante, nutriente e ricca di storia.'],['Pozol','Una bevanda ancestrale di grande tradizione.'],['Chicha di mais','Un classico che non manca mai.'],['Bevanda al cacao','Il gusto unico del cacao nicaraguense.'],['Horchata nicaraguense','Aromatica e deliziosa.']],postres:[['Quesillo','Un dolce molto amato in Nicaragua.'],['Tres Leches Nica','Morbido, cremoso e irresistibile.'],['Budino di riso','Tradizione e sapore in ogni cucchiaiata.'],['Hojaldras','Croccanti e perfette per ogni occasione.'],['Sopa Borracha','Un dolce unico della nostra cultura.'],['Dolce al cacao','Un sapore tradizionale con radici nicaraguensi.']]}
  };
  const rset=(recipeTranslations[language]?.[document.body.dataset.landing])||recipeMap[document.body.dataset.landing].es;
  recCards.forEach((c,i)=>{if(rset[i]){c.querySelector('h3').textContent=rset[i][0]; c.querySelector('p').textContent=rset[i][1]; c.querySelector('img').alt=rset[i][0];}});
  const bonusText={
    cocina:{es:'Al comprar Cocina Nicaragüense 2.0, también recibirás el bono promocional preparado para acompañar este recetario.',en:'When you buy Nicaraguan Cuisine 2.0, you will also receive the promotional bonus prepared to accompany this cookbook.',pt:'Ao comprar Culinária Nicaraguense 2.0, você também receberá o bônus promocional preparado para acompanhar este livro.',fr:'En achetant Cuisine nicaraguayenne 2.0, vous recevrez également le bonus promotionnel préparé pour accompagner ce livre.',it:'Acquistando Cucina Nicaraguense 2.0, riceverai anche il bonus promozionale preparato per accompagnare questo ricettario.'},
    bebidas:{es:'Al comprar Bebidas Nica, también recibirás el bono promocional preparado para acompañar este recetario de bebidas tradicionales.',en:'When you buy Bebidas Nica, you will also receive the promotional bonus prepared to accompany this traditional drinks collection.',pt:'Ao comprar Bebidas Nica, você também receberá o bônus promocional preparado para acompanhar esta coleção de bebidas tradicionais.',fr:'En achetant Bebidas Nica, vous recevrez également le bonus promotionnel préparé pour accompagner cette collection de boissons traditionnelles.',it:'Acquistando Bebidas Nica, riceverai anche il bonus promozionale preparato per accompagnare questa raccolta di bevande tradizionali.'},
    postres:{es:'Al comprar Postres y dulces con sabor a Nicaragua, también recibirás el bono promocional preparado para acompañar este recetario.',en:'When you buy Desserts and sweets with the flavor of Nicaragua, you will also receive the promotional bonus prepared to accompany this cookbook.',pt:'Ao comprar Doces e sobremesas com sabor da Nicarágua, você também receberá o bônus promocional preparado para acompanhar este livro.',fr:'En achetant Desserts et douceurs aux saveurs du Nicaragua, vous recevrez également le bonus promotionnel préparé pour accompagner ce livre.',it:'Acquistando Dolci e dessert al sapore del Nicaragua, riceverai anche il bonus promozionale preparato per accompagnare questo ricettario.'}
  };
  const bonusNote={es:'El bono mostrado corresponde al producto seleccionado y forma parte de la oferta de compra.',en:'The bonus shown corresponds to the selected product and is part of the purchase offer.',pt:'O bônus mostrado corresponde ao produto selecionado e faz parte da oferta de compra.',fr:'Le bonus présenté correspond au produit sélectionné et fait partie de l’offre d’achat.',it:'Il bonus mostrato corrisponde al prodotto selezionato e fa parte dell’offerta di acquisto.'};
  const bt=document.querySelector('[data-i18n="bonus_text"]'); if(bt) bt.textContent=bonusText[document.body.dataset.landing][language]||bonusText[document.body.dataset.landing].es;
  const bn=document.querySelector('[data-i18n="bonus_note"]'); if(bn) bn.textContent=bonusNote[language]||bonusNote.es;
  const offerTitle=document.querySelector('[data-i18n="offer_title"]'); if(offerTitle) offerTitle.textContent=L(page.title);
  const finalCta=document.querySelector('[data-i18n="final_cta"]'); if(finalCta) finalCta.textContent=(language==='en'?'🛒 Buy':language==='pt'?'🛒 Comprar':language==='fr'?'🛒 Acheter':language==='it'?'🛒 Acquista':'🛒 Comprar')+' '+L(page.title)+' — '+page.price+'.00';
  const footerHome=document.querySelector('[data-i18n="footer_home"]'); if(footerHome) footerHome.textContent=translations.footer_home;

  // Complete page-specific translations (kept separate so all landing pages
  // reuse the exact language selected on the main store).
  const pageText = {
    cocina:{
      recipeTitle:{es:'Algunos de los platos que encontrarás',en:'Some of the dishes you will find',pt:'Alguns dos pratos que você encontrará',fr:'Quelques-uns des plats que vous trouverez',it:'Alcuni dei piatti che troverai'},
      recipeText:{es:'Una selección visual de platos tradicionales incluidos en el recetario.',en:'A visual selection of traditional dishes included in the cookbook.',pt:'Uma seleção visual de pratos tradicionais incluídos no livro.',fr:'Une sélection visuelle de plats traditionnels inclus dans le livre.',it:'Una selezione visiva di piatti tradizionali inclusi nel ricettario.'},
      features:{es:[['Sabores de siempre','Recetas inspiradas en preparaciones tradicionales de nuestra tierra.'],['Explicado paso a paso','Contenido organizado para que puedas seguir cada preparación con mayor facilidad.'],['Para compartir','Ideal para cocinar en familia y conservar nuestras tradiciones.']],en:[['Timeless flavors','Recipes inspired by traditional preparations from our homeland.'],['Step-by-step','Organized content to help you follow each preparation with ease.'],['Made to share','Ideal for cooking with family and preserving our traditions.']],pt:[['Sabores de sempre','Receitas inspiradas em preparações tradicionais de nossa terra.'],['Explicado passo a passo','Conteúdo organizado para acompanhar cada preparação com facilidade.'],['Para compartilhar','Ideal para cozinhar em família e preservar nossas tradições.']],fr:[['Saveurs de toujours','Des recettes inspirées des préparations traditionnelles de notre terre.'],['Expliqué pas à pas','Un contenu organisé pour suivre chaque préparation plus facilement.'],['À partager','Idéal pour cuisiner en famille et préserver nos traditions.']],it:[['Sapori di sempre','Ricette ispirate alle preparazioni tradizionali della nostra terra.'],['Spiegato passo dopo passo','Contenuti organizzati per seguire ogni preparazione con facilità.'],['Da condividere','Ideale per cucinare in famiglia e conservare le nostre tradizioni.']]},
      recipes:{en:[['Gallo Pinto','Nicaragua’s most iconic dish.'],['Indio Viejo','A traditional preparation with history and flavor.'],['Baho','A unique taste of our homeland.'],['Vigorón','Yuca, pork crackling, and cabbage salad together.'],['Cheese Soup','Creamy, comforting, and delicious.'],['Nacatamal','Tradition in every bite.'],['Seafood Soup','The flavor of the sea at our table.'],['Arroz Aguado','A traditional dish for any occasion.']],pt:[['Gallo Pinto','O prato mais emblemático da Nicarágua.'],['Indio Viejo','Uma preparação tradicional com história e sabor.'],['Baho','Um sabor único de nossa terra.'],['Vigorón','A combinação de mandioca, torresmo e salada de repolho.'],['Sopa de Queijo','Cremosa, reconfortante e deliciosa.'],['Nacatamal','Tradição em cada mordida.'],['Sopa de Frutos do Mar','O sabor do mar à nossa mesa.'],['Arroz Aguado','Um prato tradicional para qualquer ocasião.']],fr:[['Gallo Pinto','Le plat le plus emblématique du Nicaragua.'],['Indio Viejo','Une préparation traditionnelle pleine d’histoire et de saveur.'],['Baho','Une saveur unique de notre terre.'],['Vigorón','Yuca, couenne de porc et salade de chou.'],['Soupe au fromage','Crémeuse, réconfortante et délicieuse.'],['Nacatamal','La tradition à chaque bouchée.'],['Soupe de fruits de mer','La saveur de la mer à notre table.'],['Arroz Aguado','Un plat traditionnel pour toutes les occasions.']],it:[['Gallo Pinto','Il piatto più iconico del Nicaragua.'],['Indio Viejo','Una preparazione tradizionale ricca di storia e sapore.'],['Baho','Un gusto unico della nostra terra.'],['Vigorón','Yuca, ciccioli e insalata di cavolo.'],['Zuppa di formaggio','Cremosa, confortante e deliziosa.'],['Nacatamal','Tradizione in ogni boccone.'],['Zuppa di frutti di mare','Il sapore del mare sulla nostra tavola.'],['Arroz Aguado','Un piatto tradizionale per ogni occasione.']]}
    },
    bebidas:{
      recipeTitle:{es:'Algunas de las bebidas que encontrarás',en:'Some of the drinks you will find',pt:'Algumas das bebidas que você encontrará',fr:'Quelques-unes des boissons que vous trouverez',it:'Alcune delle bevande che troverai'},
      recipeText:{es:'Una selección de bebidas tradicionales para conocer, preparar y compartir.',en:'A selection of traditional drinks to discover, prepare, and share.',pt:'Uma seleção de bebidas tradicionais para conhecer, preparar e compartilhar.',fr:'Une sélection de boissons traditionnelles à découvrir, préparer et partager.',it:'Una selezione di bevande tradizionali da conoscere, preparare e condividere.'},
      features:{es:[['Tradición','Recetas y sabores inspirados en nuestra cultura gastronómica.'],['Contenido organizado','Información presentada de forma práctica para consultar desde tus dispositivos.'],['Para compartir','Ideal para disfrutar en familia y conservar nuestras raíces.']],en:[['Tradition','Recipes and flavors inspired by our culinary culture.'],['Organized content','Information presented in a practical format for your devices.'],['Made to share','Ideal for enjoying with family and preserving our roots.']],pt:[['Tradição','Receitas e sabores inspirados em nossa cultura gastronômica.'],['Conteúdo organizado','Informações apresentadas de forma prática para consultar em seus dispositivos.'],['Para compartilhar','Ideal para desfrutar em família e preservar nossas raízes.']],fr:[['Tradition','Recettes et saveurs inspirées de notre culture gastronomique.'],['Contenu organisé','Des informations présentées de manière pratique sur vos appareils.'],['À partager','Idéal pour profiter en famille et préserver nos racines.']],it:[['Tradizione','Ricette e sapori ispirati alla nostra cultura gastronomica.'],['Contenuto organizzato','Informazioni presentate in modo pratico per i tuoi dispositivi.'],['Da condividere','Ideale da gustare in famiglia e per conservare le nostre radici.']]},
      recipes:{en:[['Pinolillo','An emblematic drink that represents us.'],['Tiste','Refreshing, nutritious, and full of history.'],['Pozol','An ancestral drink with deep tradition.'],['Corn Chicha','A classic that is always present.'],['Cacao Drink','The unique flavor of Nicaraguan cacao.'],['Nicaraguan Horchata','Aromatic and delicious.']],pt:[['Pinolillo','Uma bebida emblemática que nos representa.'],['Tiste','Refrescante, nutritivo e cheio de história.'],['Pozol','Uma bebida ancestral de grande tradição.'],['Chicha de Milho','Um clássico que nunca falta.'],['Bebida de Cacau','O sabor único do cacau nicaraguense.'],['Horchata Nicaraguense','Aromática e deliciosa.']],fr:[['Pinolillo','Une boisson emblématique qui nous représente.'],['Tiste','Rafraîchissante, nutritive et chargée d’histoire.'],['Pozol','Une boisson ancestrale de grande tradition.'],['Chicha de maïs','Un classique qui ne manque jamais.'],['Boisson au cacao','La saveur unique du cacao nicaraguayen.'],['Horchata nicaraguayenne','Aromatique et délicieuse.']],it:[['Pinolillo','Una bevanda emblematica che ci rappresenta.'],['Tiste','Rinfrescante, nutriente e ricca di storia.'],['Pozol','Una bevanda ancestrale di grande tradizione.'],['Chicha di mais','Un classico che non manca mai.'],['Bevanda al cacao','Il gusto unico del cacao nicaraguense.'],['Horchata nicaraguense','Aromatica e deliziosa.']]}
    },
    postres:{
      recipeTitle:{es:'Algunos de los postres y dulces que encontrarás',en:'Some of the desserts and sweets you will find',pt:'Algumas das sobremesas e doces que você encontrará',fr:'Quelques-uns des desserts et douceurs que vous trouverez',it:'Alcuni dei dolci e dessert che troverai'},
      recipeText:{es:'Una selección dulce inspirada en las tradiciones gastronómicas de Nicaragua.',en:'A sweet selection inspired by the gastronomic traditions of Nicaragua.',pt:'Uma seleção doce inspirada nas tradições gastronômicas da Nicarágua.',fr:'Une sélection sucrée inspirée des traditions gastronomiques du Nicaragua.',it:'Una selezione dolce ispirata alle tradizioni gastronomiche del Nicaragua.'},
      features:{es:[['Tradición','Recetas y sabores inspirados en nuestra cultura gastronómica.'],['Contenido organizado','Información presentada de forma práctica para consultar desde tus dispositivos.'],['Para compartir','Ideal para disfrutar en familia y conservar nuestras raíces.']],en:[['Tradition','Recipes and flavors inspired by our culinary culture.'],['Organized content','Information presented in a practical format for your devices.'],['Made to share','Ideal for enjoying with family and preserving our roots.']],pt:[['Tradição','Receitas e sabores inspirados em nossa cultura gastronômica.'],['Conteúdo organizado','Informações apresentadas de forma prática para consultar em seus dispositivos.'],['Para compartilhar','Ideal para desfrutar em família e preservar nossas raízes.']],fr:[['Tradition','Recettes et saveurs inspirées de notre culture gastronomique.'],['Contenu organisé','Des informations présentées de manière pratique sur vos appareils.'],['À partager','Idéal pour profiter en famille et préserver nos racines.']],it:[['Tradizione','Ricette e sapori ispirati alla nostra cultura gastronomica.'],['Contenuto organizzato','Informazioni presentate in modo pratico per i tuoi dispositivi.'],['Da condividere','Ideale da gustare in famiglia e per conservare le nostre radici.']]},
      recipes:{en:[['Beloved Quesillo','A beloved Nicaraguan sweet.'],['Nicaraguan Tres Leches','Soft, creamy, and irresistible.'],['Rice Pudding','Tradition and flavor in every spoonful.'],['Hojaldras','Crispy and perfect for any occasion.'],['Sopa Borracha','A unique sweet from our culture.'],['Cacao Sweet','A traditional flavor rooted in Nicaragua.']],pt:[['Quesillo','Um doce muito querido na Nicarágua.'],['Tres Leches Nica','Macio, cremoso e irresistível.'],['Arroz com Leite','Tradição e sabor em cada colherada.'],['Hojaldras','Crocantes e perfeitas para qualquer ocasião.'],['Sopa Borracha','Um doce único de nossa cultura.'],['Doce de Cacau','Um sabor tradicional com raízes nicaraguenses.']],fr:[['Quesillo','Une douceur très appréciée au Nicaragua.'],['Tres Leches nica','Doux, crémeux et irrésistible.'],['Riz au lait','Tradition et saveur à chaque cuillerée.'],['Hojaldras','Croustillantes et parfaites en toute occasion.'],['Sopa Borracha','Une douceur unique de notre culture.'],['Douceur au cacao','Une saveur traditionnelle aux racines nicaraguayennes.']],it:[['Quesillo','Un dolce molto amato in Nicaragua.'],['Tres Leches Nica','Morbido, cremoso e irresistibile.'],['Budino di riso','Tradizione e sapore in ogni cucchiaiata.'],['Hojaldras','Croccanti e perfette per ogni occasione.'],['Sopa Borracha','Un dolce unico della nostra cultura.'],['Dolce al cacao','Un sapore tradizionale con radici nicaraguensi.']]}
    }
  };
  const faq = {
    es:[['¿El libro es digital?','Sí. Es un producto digital que se entrega mediante Payhip después de completar la compra.'],['¿Puedo leerlo desde mi teléfono?','Sí. Puedes acceder al archivo digital desde dispositivos compatibles con el formato entregado por Payhip.'],['¿Cómo realizo la compra?','Presiona cualquiera de los botones de compra y serás dirigido al checkout de Payhip, donde verás las opciones disponibles.'],['¿Puedo volver a la tienda?','Sí. El encabezado y el pie de página permiten regresar a Flores Universo.']],
    en:[['Is the book digital?','Yes. It is a digital product delivered through Payhip after you complete the purchase.'],['Can I read it on my phone?','Yes. You can access the digital file from devices compatible with the format delivered by Payhip.'],['How do I purchase it?','Press any purchase button and you will be taken to the Payhip checkout, where you will see the available options.'],['Can I return to the store?','Yes. The header and footer let you return to Flores Universo.']],
    pt:[['O livro é digital?','Sim. É um produto digital entregue pelo Payhip após a conclusão da compra.'],['Posso ler no meu celular?','Sim. Você pode acessar o arquivo digital em dispositivos compatíveis com o formato entregue pelo Payhip.'],['Como faço a compra?','Pressione qualquer botão de compra e você será direcionado ao checkout do Payhip, onde verá as opções disponíveis.'],['Posso voltar à loja?','Sim. O cabeçalho e o rodapé permitem voltar para a Flores Universo.']],
    fr:[['Le livre est-il numérique ?','Oui. C’est un produit numérique livré par Payhip après la finalisation de l’achat.'],['Puis-je le lire sur mon téléphone ?','Oui. Vous pouvez accéder au fichier numérique depuis les appareils compatibles avec le format livré par Payhip.'],['Comment acheter ?','Cliquez sur l’un des boutons d’achat pour accéder au paiement Payhip et voir les options disponibles.'],['Puis-je revenir à la boutique ?','Oui. L’en-tête et le pied de page permettent de revenir à Flores Universo.']],
    it:[['Il libro è digitale?','Sì. È un prodotto digitale consegnato tramite Payhip dopo il completamento dell’acquisto.'],['Posso leggerlo dal telefono?','Sì. Puoi accedere al file digitale dai dispositivi compatibili con il formato fornito da Payhip.'],['Come posso acquistarlo?','Premi uno dei pulsanti di acquisto e verrai indirizzato al checkout Payhip, dove vedrai le opzioni disponibili.'],['Posso tornare al negozio?','Sì. L’intestazione e il piè di pagina permettono di tornare a Flores Universo.']]
  };
  const pc = pageText[document.body.dataset.landing] || pageText.cocina;
  const selected = language;
  const pick = (obj) => obj[selected] || obj.es;
  const recipeTitleEl=document.querySelector('[data-i18n="recipe_title"]'); if(recipeTitleEl) recipeTitleEl.textContent=pick(pc.recipeTitle);
  const recipeTextEl=document.querySelector('[data-i18n="recipe_text"]'); if(recipeTextEl) recipeTextEl.textContent=pick(pc.recipeText);
  const featureCards2=document.querySelectorAll('.dish-grid > div'); const fx=pick(pc.features); featureCards2.forEach((c,i)=>{if(fx[i]){c.querySelector('h3').textContent=fx[i][0];c.querySelector('p').textContent=fx[i][1];}});
  const localizedRecipes=pc.recipes[selected] || recipeMap[document.body.dataset.landing].es;
  document.querySelectorAll('.recipe-card').forEach((c,i)=>{ if(localizedRecipes[i]){c.querySelector('h3').textContent=localizedRecipes[i][0];c.querySelector('p').textContent=localizedRecipes[i][1];c.querySelector('img').alt=localizedRecipes[i][0];} });
  document.querySelectorAll('.faq details').forEach((d,i)=>{const pair=(faq[selected]||faq.es)[i];if(pair){d.querySelector('summary').textContent=pair[0];d.querySelector('p').textContent=pair[1];}});

})();
